#!/bin/bash

WORKING_PATH="$(pwd)"
SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"

cd "$SCRIPT_PATH"
if [ ! -d "vqenv" ]; then
  python3 -m venv vqenv 
  source vqenv/bin/activate
  pip install -r requirements.txt
else
  source vqenv/bin/activate
fi

cd "$WORKING_PATH"
python "$SCRIPT_PATH/seq2mkv.py" "$@"